Mineral_App/Mineral_App/mineral_log/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	url('admin/', admin.site.urls),
	url(r'', include(('minerals.urls', 'minerals'), namespace='minerals')),
	url(r'^minerals/', include(('minerals.urls', 'minerals'), namespace='minerals')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

Mineral_App/Mineral_App/minerals/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^index/$', views.index, name='index'),
	url(r'^index/(?P<letter>[A-Z])$', views.alphabet_view, name='index'),
	url(r'detail(?P<pk>\d+)/$', views.detail, name='detail'),
	url(r'detail(?P<mineral_pk>\d+)/$', views.detail, name='detail'),
	url(r'search_results/$', views.search_results, name='search_results'),
	url(r'group_view/$', views.group_view, name='group_view'),
	url(r'group_view/<(?P<group>\w+)/$', views.group_view, name='group_view'),
	url(r'', views.route, name='route'),
]

Mineral_App/Mineral_App/minerals/models.py
from django.db import models

# Create your models here.

class Mineral(models.Model):
	'''
		Model for the Mineral relation.
	'''
	name = models.CharField(max_length=300, null=True)
	img_filename = models.CharField(max_length=300, null=True)
	img_caption = models.CharField(max_length=300, null=True)
	category = models.CharField(max_length=300, null=True)
	formula = models.CharField(max_length=300, null=True)
	strunz_class = models.CharField(max_length=300, null=True)
	color = models.CharField(max_length=300, null=True)
	crystal_sys = models.CharField(max_length=300, null=True)
	unit_cell = models.CharField(max_length=300, null=True)
	crystal_sym = models.CharField(max_length=300, null=True)
	cleavage = models.CharField(max_length=300, null=True)
	mohs = models.CharField(max_length=300, null=True)
	luster = models.CharField(max_length=300, null=True)
	streak = models.CharField(max_length=300, null=True)
	diaphaneity = models.CharField(max_length=300, null=True)
	optical_prop = models.CharField(max_length=300, null=True)
	refractive_inx = models.CharField(max_length=300, null=True)
	crystal_habit = models.CharField(max_length=300, null=True)
	spec_gravity = models.CharField(max_length=300, null=True)

Mineral_App/Mineral_App/minerals/forms.py
from django import forms

class SearchBar(forms.ModelForm):
	search = forms.CharField(
				widget=forms.TextInput(
					attrs={'placeholder': 'Search for minerals by their name!'}
				)
			)
			

Mineral_App/Mineral_App/minerals/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
import re

from .models import Mineral
from . import forms


def in_group(str):
	groups = ['silicate', 'oxide', 'sulfate', 'sulfide', 'carbonate',
				'halide', 'sulfosalt', 'phosphate', 'borate', 'organic',
				'arsenate', 'native']
	for group in groups:
		if group in str.lower():
			return True;
	return False;
	
def route(request):
	'''Reroutes to the index view.'''
	minerals=Mineral.objects.filter(name__startswith='A')
	return render(request, 'minerals/index.html', {'minerals': minerals})
	
	
def index(request, letter):
	'''Returns a list of all the minerals in the database.'''
	minerals = Mineral.objects.filter(name__startswith=letter)
	return render(request, 'minerals/index.html', {'minerals': minerals})
	
def alphabet_view(request, letter):
	'''
	Returns a list of all the minerals beginning with 
	a specified letter.
	'''
	minerals = Mineral.objects.filter(name__startswith=letter)
	return render(request, 'minerals/index.html', {'minerals': minerals})
	
def detail(request, pk):
	'''Returns a detailed view of a single mineral.'''
	mineral = get_object_or_404(Mineral, pk=pk)
	return render(request, 'minerals/mineral_detail.html', {'mineral': mineral})
	
def search_results(request):
	'''Returns a listing of minerals matching the search.'''
	query = request.GET.get('q')
	if query:
		minerals = Mineral.objects.filter(name__icontains=query)
		return render(request, 'minerals/index.html', {'minerals': minerals})
	else:
		minerals = []
		return render(request, 'minerals/index.html', {'minerals': minerals})
		
def group_view(request, group):
	'''Returns a listing of minerals matching the given group.'''
	if group != 'other':
		minerals = Mineral.objects.filter(category__icontains=group)
		return render(request, 'minerals/index.html', {'minerals': minerals})
	else:
		minerallist = Mineral.objects.all()
		minerals = set()
		for mineral in minerallist:
			if not in_group(mineral.category):
				minerals.add(mineral)
		return render(request, 'minerals/index.html', {'minerals': minerals})

Mineral_App/Mineral_App/minerals/templates/minerals/index.html
{% extends 'minerals/layout.html' %}

{% load static %}

{% block content %}

<div class="minerals__container">

{% for mineral in minerals %}
		<div class="minerals__anchor"><a href="{% url 'minerals:detail' pk=mineral.pk %}">{{ mineral.name }}</a>
			</div>
{% endfor %}
</div>
{% endblock %}

Mineral_App/Mineral_App/minerals/templates/minerals/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<title>Mucho Minerals</title>
		<link rel="stylesheet" href="{% static 'assets/css/global.css' %}">
	</head>
	
	
	
	
	<body>
	<div class="logo-margin">
	<div class="logo">
		<img src="/static/images/430094-64.png" />
		<header class="logo__name">{% block title %}<a href="{% url 'minerals:index' 'A' %}">Mucho Minerales{% endblock %}</a></header>
	</div>
	</div>
	
	<div id="groups">
	<div class="group-table">
		<ul id="vertical-list">
			<li><a class="{% if request.path == '/group_view/<silicate/' %}bold-white{% endif %}" href="{% url 'minerals:group_view' group='silicate' %}">Silicates</a></li>
			<li><a class="{% if request.path == '/group_view/<oxide/' %}bold-white{% endif %}" href="{% url 'minerals:group_view' group='oxide' %}">Oxides</a></li>
			<li><a class="{% if request.path == '/group_view/<sulfate/' %}bold-white{% endif %}" href="{% url 'minerals:group_view' group='sulfate' %}">Sulfates</a></li>
			<li><a class="{% if request.path == '/group_view/<carbonate/' %}bold-white{% endif %}" href="{% url 'minerals:group_view' group='carbonate' %}">Carbonates</a></li>
			<li><a class="{% if request.path == '/group_view/<halide/' %}bold-white{% endif %}" href="{% url 'minerals:group_view' group='halide' %}">Halides</a></li>
			<li><a class="{% if request.path == '/group_view/<sulfosalt/' %}bold-white{% endif %}" href="{% url 'minerals:group_view' group='sulfosalt' %}">Sulfosalts</a></li>
			<li><a class="{% if request.path == '/group_view/<phosphate/' %}bold-white{% endif %}" href="{% url 'minerals:group_view' group='phosphate' %}">Phosphates</a></li>
			<li><a class="{% if request.path == '/group_view/<borate/' %}bold-white{% endif %}" href="{% url 'minerals:group_view' group='borate' %}">Borates</a></li>
			<li><a class="{% if request.path == '/group_view/<organic/' %}bold-white{% endif %}" href="{% url 'minerals:group_view' group='organic' %}">Organic Minerals</a></li>
			<li><a class="{% if request.path == '/group_view/<arsenate/' %}bold-white{% endif %}" href="{% url 'minerals:group_view' group='arsenate' %}">Arsenates</a></li>
			<li><a class="{% if request.path == '/group_view/<native/' %}bold-white{% endif %}" href="{% url 'minerals:group_view' group='native' %}">Native Elements</a></li>
			<li><a class="{% if request.path == '/group_view/<other/' %}bold-white{% endif %}" href="{% url 'minerals:group_view' group='other' %}">Other</a></li>
		</ul>
	</div>
	</div>
	<!-- Search Bar -->
	<div id="list">
	<div class="menu-table">
		<ul id="horizontal-list">
		<div>
			<li><a class="{% if request.path == '/index/A' %}bold{% endif %}" href="{% url 'minerals:index' 'A' %}">A</a></li>
			<li><a class="{% if request.path == '/index/B' %}bold{% endif %}" href="{% url 'minerals:index' 'B' %}">B</a></li>
			<li><a class="{% if request.path == '/index/C' %}bold{% endif %}" href="{% url 'minerals:index' 'C' %}">C</a></li>
			<li><a class="{% if request.path == '/index/D' %}bold{% endif %}" href="{% url 'minerals:index' 'D' %}">D</a></li>
			<li><a class="{% if request.path == '/index/E' %}bold{% endif %}" href="{% url 'minerals:index' 'E' %}">E</a></li>
			<li><a class="{% if request.path == '/index/F' %}bold{% endif %}" href="{% url 'minerals:index' 'F' %}">F</a></li>
			<li><a class="{% if request.path == '/index/G' %}bold{% endif %}" href="{% url 'minerals:index' 'G' %}">G</a></li>
			<li><a class="{% if request.path == '/index/H' %}bold{% endif %}" href="{% url 'minerals:index' 'H' %}">H</a></li>
			<li><a class="{% if request.path == '/index/I' %}bold{% endif %}" href="{% url 'minerals:index' 'I' %}">I</a></li>
			<li><a class="{% if request.path == '/index/J' %}bold{% endif %}" href="{% url 'minerals:index' 'J' %}">J</a></li>
			<li><a class="{% if request.path == '/index/K' %}bold{% endif %}" href="{% url 'minerals:index' 'K' %}">K</a></li>
			<li><a class="{% if request.path == '/index/L' %}bold{% endif %}" href="{% url 'minerals:index' 'L' %}">L</a></li>
			<li><a class="{% if request.path == '/index/M' %}bold{% endif %}" href="{% url 'minerals:index' 'M' %}">M</a></li>
			<li><a class="{% if request.path == '/index/N' %}bold{% endif %}" href="{% url 'minerals:index' 'N' %}">N</a></li>
			<li><a class="{% if request.path == '/index/O' %}bold{% endif %}" href="{% url 'minerals:index' 'O' %}">O</a></li>
			<li><a class="{% if request.path == '/index/P' %}bold{% endif %}" href="{% url 'minerals:index' 'P' %}">P</a></li>
			<li><a class="{% if request.path == '/index/Q' %}bold{% endif %}" href="{% url 'minerals:index' 'Q' %}">Q</a></li>
			<li><a class="{% if request.path == '/index/R' %}bold{% endif %}" href="{% url 'minerals:index' 'R' %}">R</a></li>
			<li><a class="{% if request.path == '/index/S' %}bold{% endif %}" href="{% url 'minerals:index' 'S' %}">S</a></li>
			<li><a class="{% if request.path == '/index/T' %}bold{% endif %}" href="{% url 'minerals:index' 'T' %}">T</a></li>
			<li><a class="{% if request.path == '/index/U' %}bold{% endif %}" href="{% url 'minerals:index' 'U' %}">U</a></li>
			<li><a class="{% if request.path == '/index/V' %}bold{% endif %}" href="{% url 'minerals:index' 'V' %}">V</a></li>
			<li><a class="{% if request.path == '/index/W' %}bold{% endif %}" href="{% url 'minerals:index' 'W' %}">W</a></li>
			<li><a class="{% if request.path == '/index/X' %}bold{% endif %}" href="{% url 'minerals:index' 'X' %}">X</a></li>
			<li><a class="{% if request.path == '/index/Y' %}bold{% endif %}" href="{% url 'minerals:index' 'Y' %}">Y</a></li>
			<li><a class="{% if request.path == '/index/Z' %}bold{% endif %}" href="{% url 'minerals:index' 'Z' %}">Z</a></li>
		</div>
		</ul>
	
	</div>
	</div>
	
	<!-- Search Form -->
	<div class="searchbar">
	<form id="searchbar" method="GET" action="{% url 'minerals:search_results' %}">
		<input class="input-button-home" type="submit" value="Search" />
		<div class="input-home">
		<input type="text" name='q' style="width:100%" />
		</div>
	</form>
	</div>
	
	{% block content %}{% endblock %}
	</body>
</html>

Mineral_App/Mineral_App/minerals/templates/minerals/mineral_detail.html
{% extends 'minerals/layout.html' %}

{% load static %}
{% block content %}
<title>Mineral Details</title>
	<div class="mineral__container">
	<article>
		<div class="mineral__name">
			<h2>{{ mineral.name }}</h2>
		</div>
		<div class="mineral__caption">
			<h3>{{ mineral.img_caption|title }}</h3>
		</div>
		<div class="mineral__image-bg">
			<img class="mineral__image" src="{% static 'images' %}/{{ mineral.img_filename }}" alt="{{ mineral.img_filename }}" height="100px" width="100px">
		</div>
		<div class="mineral__table-container">
			<div class="mineral__category">
			<table class="mineral__table">
					<tr>
						<td>Category: {{ mineral.category|title }}</td>
					</tr>
				
					<tr>
						<td>Formula: {{ mineral.formula|title }}</td>
					</tr>
					<tr>
						<td>Strunz Class: {{ mineral.strunz_class|title }}</td>
					</tr>
					<tr>
						<td>Color: {{ mineral.color|title }}</td>
					</tr>
					<tr>
						<td>Crystal System: {{ mineral.crystal_sys|title }}</td>
					</tr>
					<tr>
						<td>Unit Cell: {{ mineral.unit_cell|title }}</td>
					<tr>
						<td>Crystal Symmetry: {{ crystal_sym|title }}</td>
					</tr>
					<tr>
						<td>Cleavage: {{ mineral.cleavage|title }}</td>
					</tr>
					<tr>
						<td>Mohs Scale Hardness: {{ mineral.mohs|title }}</td>
					</tr>
					<tr>
						<td>Luster: {{ mineral.luster|title }}</td>
					</tr>
					<tr>
						<td>Streak: {{ mineral.streak|title }}</td>
					</tr>
					<tr>
						<td>Diaphaneity: {{ mineral.diaphaneity|title }}</td>
					</td>
					<tr>
						<td>Optical Properties: {{ mineral.optical_prop|title }}</td>
					</tr>
					<tr>
						<td>Refractive Index: {{ mineral.refractive_inx|title }}</td>
					</tr>
					<tr>
						<td>Crystal Habit: {{ mineral.crystal_hab|title }}</td>
					</tr>
					<tr>
						<td>Specific Gravity: {{ mineral.spec_grav|title }}</td>
					</tr>
				</div>
			</table>
		</div>
	</article>
	</div>
	{% endblock %}

Mineral_App/Mineral_App/minerals/templates/minerals/search.html
{% extends 'layout.html' %}

{% block content %}

{% endblock %}